"""criar_tabelas_inicio

Revision ID: 21751b185346
Revises: 9998a120a0cc
Create Date: 2025-02-23 11:40:40.746726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21751b185346'
down_revision: Union[str, None] = '9998a120a0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispositivo',
    sa.Column('id_dispositivo', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ds_nome', sa.String(length=255), nullable=False),
    sa.Column('tp_dispositivo', sa.Enum('RASPBERRY', 'CLP', name='tipodispositivo', native_enum=False), nullable=False),
    sa.Column('ds_localizacao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_dispositivo')
    )
    op.create_table('unidade_medida',
    sa.Column('id_unidade_medida', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ds_denominacao', sa.String(length=50), nullable=False),
    sa.Column('ds_sigla', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id_unidade_medida')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ds_nome', sa.String(length=255), nullable=False),
    sa.Column('ds_username', sa.String(length=100), nullable=False),
    sa.Column('ds_email', sa.String(length=255), nullable=False),
    sa.Column('ds_senha', sa.String(length=400), nullable=False),
    sa.Column('tp_usuario', sa.Enum('ADMIN', 'COMUM', name='tipousuario', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('ds_email'),
    sa.UniqueConstraint('ds_username')
    )
    op.create_table('sensor',
    sa.Column('id_sensor', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ds_nome', sa.String(length=255), nullable=False),
    sa.Column('tp_sensor', sa.Enum('TEMPERATURA', 'VAZAO', 'PRESSAO', name='tiposensor', native_enum=False), nullable=False),
    sa.Column('dispositivo_id_dispositivo', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_id_dispositivo'], ['dispositivo.id_dispositivo'], ),
    sa.PrimaryKeyConstraint('id_sensor')
    )
    op.create_table('medicao',
    sa.Column('id_medicao', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sensor_id_sensor', sa.BigInteger(), nullable=False),
    sa.Column('unidade_medida_id_unidade_medida', sa.BigInteger(), nullable=False),
    sa.Column('vl_valor', sa.Float(), nullable=False),
    sa.Column('dt_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id_sensor'], ['sensor.id_sensor'], ),
    sa.ForeignKeyConstraint(['unidade_medida_id_unidade_medida'], ['unidade_medida.id_unidade_medida'], ),
    sa.PrimaryKeyConstraint('id_medicao')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicao')
    op.drop_table('sensor')
    op.drop_table('usuario')
    op.drop_table('unidade_medida')
    op.drop_table('dispositivo')
    # ### end Alembic commands ###
