"""adicionar coluna codigo

Revision ID: 04c4072715af
Revises: c31e7dc69353
Create Date: 2025-03-30 15:46:57.345919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c4072715af'
down_revision: Union[str, None] = 'c31e7dc69353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispositivo', sa.Column('cd_dispositivo', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'dispositivo', ['cd_dispositivo'])
    op.add_column('sensor', sa.Column('cd_sensor', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'sensor', ['cd_sensor'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor', type_='unique')
    op.drop_column('sensor', 'cd_sensor')
    op.drop_constraint(None, 'dispositivo', type_='unique')
    op.drop_column('dispositivo', 'cd_dispositivo')
    # ### end Alembic commands ###
