"""criar tabela coleta e ajustar medicao

Revision ID: 59641a7c137d
Revises: 04c4072715af
Create Date: 2025-04-17 21:26:56.331858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '59641a7c137d'
down_revision: Union[str, None] = '04c4072715af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coleta',
    sa.Column('id_coleta', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dt_hora', sa.DateTime(), nullable=True),
    sa.Column('origem', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_coleta')
    )
    op.add_column('medicao', sa.Column('coleta_id_coleta', sa.BigInteger(), nullable=True))
    op.add_column('medicao', sa.Column('vl_valor_str', sa.String(length=255), nullable=True))
    op.add_column('medicao', sa.Column('vl_valor_bool', sa.Boolean(), nullable=True))
    op.alter_column('medicao', 'vl_valor',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.create_foreign_key(None, 'medicao', 'coleta', ['coleta_id_coleta'], ['id_coleta'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medicao', type_='foreignkey')
    op.alter_column('medicao', 'vl_valor',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.drop_column('medicao', 'vl_valor_bool')
    op.drop_column('medicao', 'vl_valor_str')
    op.drop_column('medicao', 'coleta_id_coleta')
    op.drop_table('coleta')
    # ### end Alembic commands ###